// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileApplication;

namespace MobileApplication.Migrations
{
    [DbContext(typeof(MobileDbContext))]
    [Migration("20210205192443_MobileDetailsAdded")]
    partial class MobileDetailsAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MobileApplication.Models.MobileBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("MobileApplication.Models.MobileDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Battery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DisplaySize")
                        .HasColumnType("float");

                    b.Property<int?>("MobileBrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Processor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isBluetoothSupport")
                        .HasColumnType("bit");

                    b.Property<bool>("isWIFISupport")
                        .HasColumnType("bit");

                    b.Property<double>("weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MobileBrandId");

                    b.ToTable("productDetails");
                });

            modelBuilder.Entity("MobileApplication.Models.MobileDetails", b =>
                {
                    b.HasOne("MobileApplication.Models.MobileBrand", "LeaveType")
                        .WithMany()
                        .HasForeignKey("MobileBrandId");

                    b.Navigation("LeaveType");
                });
#pragma warning restore 612, 618
        }
    }
}
